## Week 2: Review of Python data structures

This notebook contains six exercises, to help you review some basic Python data structures, and their manipulations.
The first three are for the workshop.
The last three are for hand-in on GitHub by 9:30am on Friday, 30 January (together with the problems from Week 1).

## Marking

You will get hand-in marks for completing these questions:


| <p align='left'> Title                         | <p align='left'> Parts | <p align='left'> Number of marks | <p align='left'> Marks awarded |
| ------------------------------------- | ----- | --- | --- |
| <p align='left'> 4. Boolean indexing vs. loops      | <p align='left'>  2  | <p align='left'>  1 | <p align='left'>  |
| <p align='left'> 5. Data structures and efficient search | <p align='left'>  2  | <p align='left'>  2 | <p align='left'>  |
| <p align='left'> 6. Large Pandas dataframe & compounted filters       | <p align='left'>  2  | <p align='left'>  2 | <p align='left'>  |
| <p align='left'> **Total** | | <p align='left'> max **5** | <p align='left'> |
| <p align='left'> **Total of Weeks 1 and 2** | | <p align='left'> max **10** | <p align='left'> |

## Question 1: 2×2 Determinant (nested lists)

You are given two 2×2 matrices as **lists of lists** (a list of rows):
```python
A = [[3, 8],
     [4, 6]]

B = [[1, 2],
     [3, 4]]
```

Write a function `det2(M)` that returns the determinant of a 2×2 matrix:
- If `M = [[a, b], [c, d]]`, then `det(M) = a*d - b*c`.

Finish the function below by replacing `## FINISH_ME ##` with the correct expression.

Docs:
- Python lists (indexing): https://docs.python.org/3/tutorial/introduction.html#lists
- Sequence types / indexing `M[r][c]`: https://docs.python.org/3/library/stdtypes.html#typesseq

In [1]:
A = [[3, 8],
     [4, 6]]

B = [[1, 2],
     [3, 4]]

def det2(M):
    
    out = 0.0
    out += M[0][0] * M[1][1] - M[0][1] * M[1][0]

    return out

print('det(A) should be -14 ->', det2(A))
print('det(B) should be -2  ->', det2(B))

det(A) should be -14 -> -14.0
det(B) should be -2  -> -2.0


## Question 2: Find the numeric key in a dictionary

You are given a dictionary where most keys are **single characters** (like `'a'`, `'b'`, `'x'`) but **one key is actually a number** (an `int`).

Write a function that loops through the keys and finds the key that is an `int`, then returns the value stored at that key.

Example dictionary:
```python
d = {'a': 'apple', 'b': 'banana', 7: 'seven', 'z': 'zebra'}
```

In this example, the numeric key is `7`, so the function should return `'seven'`.

Finish the function below. Keep it simple: use a `for` loop and `isinstance(k, int)`.

Docs:
- Dictionaries (iteration over keys): https://docs.python.org/3/library/stdtypes.html#mapping-types-dict
- `isinstance`: https://docs.python.org/3/library/functions.html#isinstance

In [2]:
d1 = {'a': 'apple', 'b': 'banana', 7: 'seven', 'z': 'zebra'}
d2 = {'x': 100, 'y': 200, 42: 999, 'q': 0}

def value_at_numeric_key(d):
    """Return the value at the numeric key in dictionary d by using type checking."""

    for key in d.keys():
        if isinstance(key, int):
            return d[key]

    return None

print('d1 expected seven ->', value_at_numeric_key(d1))
print('d2 expected 999   ->', value_at_numeric_key(d2))

d1 expected seven -> seven
d2 expected 999   -> 999


## Question 3: 2D list → NumPy → pandas → PyTorch

You are given a 2D Python list (a list of rows):
```python
data = [
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]
```

Complete the code in the next cell so it:
1) Converts the 2D list into a **NumPy array**
2) Converts that into a **pandas DataFrame** (give the columns names)
3) Converts the NumPy array into a **PyTorch tensor**

Replace each `## FINISH_ME ##` with the correct code.

Docs:
- `numpy.array`: https://numpy.org/doc/stable/reference/generated/numpy.array.html
- `pandas.DataFrame`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html
- `torch.tensor`: https://pytorch.org/docs/stable/generated/torch.tensor.html

In [3]:
import numpy as np
import pandas as pd
import torch

In [4]:
# Fill in the FINISH_ME parts

data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

arr = np.array(data)          # NumPy array from data
df  = pd.DataFrame(arr, columns=["Column1", "This is also a column", "Yippee Primary gave me a name"])            # DataFrame from arr (name your columns)
ten = torch.tensor(arr)            # PyTorch tensor from arr

if arr is None or df is None or ten is None:
    print("Please complete the FINISH_ME parts of the code.")
else:
    
    print('type(arr):', type(arr), 'shape:', arr.shape)
    print('type(df):', type(df), 'shape:', df.shape)
    print('type(ten):', type(ten), 'shape:', tuple(ten.shape))

    print('\nNumPy array preview:')
    print(arr)

    print('\nDataFrame preview:')
    print(df.head())

    print('\nTensor preview:')
    print(ten)

type(arr): <class 'numpy.ndarray'> shape: (3, 3)
type(df): <class 'pandas.core.frame.DataFrame'> shape: (3, 3)
type(ten): <class 'torch.Tensor'> shape: (3, 3)

NumPy array preview:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

DataFrame preview:
   Column1  This is also a column  Yippee Primary gave me a name
0        1                      2                              3
1        4                      5                              6
2        7                      8                              9

Tensor preview:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


## Question 4: Built-in library data access is faster than a Python for-loop

This question demonstrates why **NumPy built-ins** (vectorized operations) are usually faster than looping in Python.

You will make a large array of random values; then choose a threshold (equal to 0.5 below), and filter the values that are above the threshhold in two ways:
1) A plain Python `for` loop
2) NumPy boolean indexing (built-in)

Your job: fill in the `## FINISH_ME ##` line to use NumPy boolean indexing, then compare the timings.

Docs:
- NumPy boolean indexing: https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing
- `time.perf_counter`: https://docs.python.org/3/library/time.html#time.perf_counter

Bonus (for your own fun): you could also try using list comprehension to filter the values
- https://docs.python.org/3/tutorial/datastructures.html
How does its timing compare to a standard `for` and boolean indexing?

In [5]:
import time
import numpy as np

# Make a big 1D array of random numbers
rng = np.random.default_rng(0)     # random number generator
x = rng.random(1_000_000)  # try increasing to 1_000_000 if you want a bigger difference
threshold = 0.5

# 1) Python for-loop filter
t0 = time.perf_counter()
out_loop = []
for v in x:
    if v > threshold:
        out_loop.append(v)
t1 = time.perf_counter()

# 2) NumPy built-in (boolean indexing)
t2 = time.perf_counter()
out_np = np.array(x)
out_np = out_np[out_np > threshold]
t3 = time.perf_counter()

print('loop result length:', len(out_loop))
print('numpy result length:', len(out_np))
print('same length?', len(out_loop) == len(out_np))

print(f'for-loop time: {(t1 - t0)*1000:.2f} ms')
print(f'numpy time:    {(t3 - t2)*1000:.2f} ms')

loop result length: 499806
numpy result length: 499806
same length? True
for-loop time: 385.46 ms
numpy time:    31.81 ms


## Question 5: Student records — what data structure is most efficient?

You are given some mock student record data. Each record contains:
- `student_id` (an int)
- `name` (a string)
- `courses` (a list of course results)

A *course result* looks like:
```python
{'course': 'MATH101', 'score': 72, 'passed': True}
```

### Task
You need to answer queries like:
- “Return **all students who passed** `MATH101`.”

### Think first
What is the most efficient way to store the data for fast lookup?
- A list of records?
- A dictionary keyed by `student_id`?
- A dictionary keyed by course name (called an "index" in this context)?

In the next cell, build a structure that makes the query fast, then return the list of names who passed a given course.

Docs:
- Dictionaries (key → value lookups): https://docs.python.org/3/library/stdtypes.html#mapping-types-dict
- Data structures overview (lists/dicts): https://docs.python.org/3/tutorial/datastructures.html

In [10]:
# Mock student records (list of dicts)
students = [
    {
        'student_id': 1001,
        'name': 'Ava',
        'courses': [
            {'course': 'MATH101', 'score': 72, 'passed': True},
            {'course': 'PHYS101', 'score': 61, 'passed': True},
        ],
    },
    {
        'student_id': 1002,
        'name': 'Ben',
        'courses': [
            {'course': 'MATH101', 'score': 48, 'passed': False},
            {'course': 'CS101', 'score': 83, 'passed': True},
        ],
    },
    {
        'student_id': 1003,
        'name': 'Chen',
        'courses': [
            {'course': 'MATH101', 'score': 90, 'passed': True},
            {'course': 'CS101', 'score': 55, 'passed': True},
        ],
    },
    {
        'student_id': 1004,
        'name': 'Dina',
        'courses': [
            {'course': 'PHYS101', 'score': 45, 'passed': False},
            {'course': 'MATH101', 'score': 67, 'passed': True},
        ],
    },
    {
        'student_id': 1005,
        'name': 'Eli',
        'courses': [
            {'course': 'CS101', 'score': 49, 'passed': False},
            {'course': 'MATH101', 'score': 51, 'passed': True},
        ],
    },
    {
        'student_id': 1006,
        'name': 'Fatima',
        'courses': [
            {'course': 'MATH101', 'score': 29, 'passed': False},
            {'course': 'PHYS101', 'score': 77, 'passed': True},
        ],
    },
    {
        'student_id': 1007,
        'name': 'Gus',
        'courses': [
            {'course': 'MATH101', 'score': 100, 'passed': True},
        ],
    },
    {
        'student_id': 1008,
        'name': 'Hana',
        'courses': [
            {'course': 'CS101', 'score': 92, 'passed': True},
            {'course': 'MATH101', 'score': 60, 'passed': True},
        ],
    },
    {
        'student_id': 1009,
        'name': 'Ivan',
        'courses': [
            {'course': 'PHYS101', 'score': 59, 'passed': False},
            {'course': 'MATH101', 'score': 58, 'passed': True},
        ],
    },
    {
        'student_id': 1010,
        'name': 'Jo',
        'courses': [
            {'course': 'MATH101', 'score': 62, 'passed': True},
            {'course': 'CS101', 'score': 12, 'passed': False},
        ],
    },
]

# Now, assuming the ONLY question you will be asked is "which students passed course X?",
# build a database (using the data above) that makes answering the question fast.
# Hint: dictionary lookup is fast...  e.g. you could create something with entries like {'MATH101': ['Ava', 'Chen', ...], ...}

def build_pass_database(records):
    """Return a reorganized database."""
    database = {}
    found_courses = []
    for student in records:
        for course in student['courses']:
            if course['passed']:
                course_name = course['course']
                if course_name in found_courses:
                    database[course_name].append(student['name'])
                else:
                    found_courses.append(course_name)
                    database[course_name] = [student['name']]
    return database

# Then define a function that searches the database.
# Its arguments are the database (in the format you created above) and the name of a course,
# and its output should be the list of students who passed that course.

def passed_students(database, course):
    """Return list of student names who passed `course`."""
    return database.get(course,None)

pass_database = build_pass_database(students)
print('MATH101 passed:', passed_students(pass_database, 'MATH101'))
print('PHYS101 passed:', passed_students(pass_database, 'PHYS101'))
print('CS101 passed:', passed_students(pass_database, 'CS101'))

MATH101 passed: ['Ava', 'Chen', 'Dina', 'Eli', 'Gus', 'Hana', 'Ivan', 'Jo']
PHYS101 passed: ['Ava', 'Fatima']
CS101 passed: ['Ben', 'Chen', 'Hana']


## Question 6: Large pandas DataFrame + compounded filters

In this question you will:
1) Generate a **large(ish)** pandas DataFrame with multiple columns
2) Write **one compound filter** (multiple conditions combined) to select a subset of rows

You’ll practice:
- Comparisons like `>=`, `<=`
- Combining conditions with `&` (AND) and `|` (OR)
- `.isin(...)` for membership checks
- `.between(a, b)` for ranges
- String filters like `.str.contains(...)`

Complete the `## FINISH_ME ##` parts in the next cell.

Docs:
- Numpy's random number generator: https://numpy.org/doc/stable/reference/random/generator.html
- Pandas boolean indexing: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing
- `.loc` selection: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html
- `Series.isin`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html
- `Series.between`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.between.html

In [51]:
import numpy as np
import pandas as pd

# ----------------------------
# Part A: Generate mock records
# ----------------------------
rng = np.random.default_rng(123)
N = 200_000  # large(ish)
regions = np.array(['NA', 'EU', 'APAC'])
departments = np.array(['Physics', 'Math', 'CS', 'Chem'])
courses = np.array(['MATH101', 'PHYS101', 'CS101', 'CHEM101'])
statuses = np.array(['enrolled', 'dropped', 'completed'])

## Remember to make a random choice using numpy built-ins you can use rng.choice(possible_values, output_length)

# Make sure we populate the dataframe with 200k entries for each column

df_big = pd.DataFrame({
    'student_id': range(100000,100000+N),         # Replace with a range starting at 100000 with unique ID for all students (running to 100_000 + N)
    'region': rng.choice(regions,N),             # Randomly select a region for each student
    'department': rng.choice(departments,N),         # Randomly select a department for each student
    'course': rng.choice(courses,N),             # Randomly select a course for each student
    'status': rng.choice(statuses,N,p=[0.45,0.10,0.45]),             # Randomly select status with the following probability weights p=[0.45,0.10,0.45]
    'score': rng.integers(0,101,N),              # Randomly select score for each student between 0 and 100 (including 100)
    'attendance':rng.integers(60,101,N),         # Randomly select the attendance number for each student between 60 and 100
    'study_hours': rng.normal(10,3,N),        # Randomly select the number of study hours per student from a normal distribution, with mean 10 and standard deviation 3
})

# Add a simple text column (for string filtering)
df_big['email'] = 'student' + df_big['student_id'].astype(str) + '@AGQ.edu'

print('df_big shape:', df_big.shape)
print(df_big.head(3))

# -----------------------------------
# Part B: Compounded query (your turn)
# -----------------------------------
# Select rows where ALL of these are true:
#   1) course is MATH101 or CS101
#   2) status is completed
#   3) score >= 60
#   4) attendance between 80 and 100 (inclusive)
#   5) region is NA or EU
# Then return a DataFrame containing ONLY these columns (in this order):
#   ['student_id', 'email', 'region', 'course', 'score', 'attendance']

mask =  df_big.where((df_big['course'].isin(['MATH101','CS101'])) &
                     (df_big['status'] == 'completed') &
                     (df_big['score'] >= 60) &
                     (df_big['attendance'].between(80,100) ) &
                     (df_big['region'].isin(['NA','EU']))).dropna() 

subset = mask[['student_id', 'email', 'region', 'course', 'score', 'attendance']] # use "mask" to select the desired subset of rows, then select and reorder the columns


predicted_count = int(
    0.5  # courses MATH101 or CS101
    * 0.45  # status completed
    * 0.40  # score >= 60
    * 0.50  # attendance between 80 and 100
    * (2/3)  # region NA or EU
    * N
)

number_of_rows = mask.size / 9

if mask is None or subset is None:
    print("Please complete the FINISH_ME parts of the code.")
else:

    print('\n\n-----------------------------------')

    print('predicted number of rows passing filter:', predicted_count)
    print('mask sum:', number_of_rows)

    print('%-age difference between predicted and actual:',
          abs(number_of_rows - predicted_count) / predicted_count * 100, '%')

    print('-----------------------------------\n\n')

    print('subset shape:', subset.shape)
    print(subset.head(5))

    # Quick self-checks (should all be True if your filter is correct)
    #if isinstance(mask, (pd.Series, np.ndarray)) and hasattr(subset, 'columns'):   # SH: I removed the isinstance(mask,..) since I didn't do it that way, but it still works.
    #                                                                                 I am unconvinced of the benefits of not using the built-in methods.
    if hasattr(subset, 'columns'):
        ok = True
        ok = ok and subset['course'].isin(['MATH101', 'CS101']).all()
        ok = ok and (subset['status'] == 'completed').all() if 'status' in subset.columns else ok
        ok = ok and (subset['score'] >= 60).all()
        ok = ok and subset['attendance'].between(80, 100).all()
        ok = ok and subset['region'].isin(['NA', 'EU']).all()
        
        print('\n\n\nchecks passed?', ok, '\n')
    else:
        print('Please complete the FINISH_ME parts of the code.')

df_big shape: (200000, 9)
   student_id region department   course     status  score  attendance  \
0      100000     NA         CS  MATH101  completed     23          75   
1      100001   APAC    Physics  MATH101   enrolled     38          66   
2      100002     EU         CS  PHYS101    dropped     34          97   

   study_hours                  email  
0    11.731623  student100000@AGQ.edu  
1    16.436467  student100001@AGQ.edu  
2     8.213530  student100002@AGQ.edu  


-----------------------------------
predicted number of rows passing filter: 6000
mask sum: 6297.0
%-age difference between predicted and actual: 4.95 %
-----------------------------------


subset shape: (6297, 6)
     student_id                  email region   course  score  attendance
41     100041.0  student100041@AGQ.edu     NA  MATH101   78.0        97.0
72     100072.0  student100072@AGQ.edu     EU  MATH101   80.0       100.0
101    100101.0  student100101@AGQ.edu     NA  MATH101   95.0        84.0
147 